### Indexing & Slicing: The Art of Extracting Data from Sequences

**Syntax rules**
- start  – first index to include (default 0)
- stop  – index to stop before (excluded, default = len(seq))
- step  – increment between indices (default 1, cannot be 0)

In [1]:
# Simple indexing

s = "python"

print(s[0]) # first element of string
print(s[-1]) # last element of string

p
n


In [7]:
# Slicing

print(s[0:])
print(s[:6])
print(s[::-1])
print(s[::2])

python
python
nohtyp
pto


In [8]:
nums = [0,1,2,3,4,5]
nums[1:4] = [100,200]
print(nums)

[0, 100, 200, 4, 5]


In [9]:
# Delete Slice

nums[2:4] = []
print(nums)

[0, 100, 5]


In [12]:
# Using slice() built-in

s = slice(1, 10, 2)

text = "Indexing & Slicing"
print(text[s])

neig&


In [17]:
# Ellipsis slicing ( ... ) – used in NumPy/TensorFlow for multi‑dimensional arrays

import numpy as np
arr = np.arange(24).reshape(2,3,4)
print(arr,"\n")
print(arr[..., 1],"\n")   # all rows, all columns, only index 1 of last dimension
# Equivalent to arr[:, :, 1]
print(arr[:,:,1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

[[ 1  5  9]
 [13 17 21]] 

[[ 1  5  9]
 [13 17 21]]
